/**This class is automatically generated by LayaAirIDE, please do not make any modifications. */
import View=Laya.View;
import Dialog=Laya.Dialog;
import Scene=Laya.Scene;
var REG: Function = Laya.ClassUtils.regClass;
export module ui.test {
    export class TestSceneUI extends Scene {
        public static  uiView:any ={"type":"Scene","props":{"width":640,"runtime":"script/GameUI.ts","name":"gameBox","height":1136},"compId":1,"loadList":[],"loadList3D":[]};
        constructor(){ super()}
        createChildren():void {
            super.createChildren();
            this.createView(TestSceneUI.uiView);
        }
    }
    REG("ui.test.TestSceneUI",TestSceneUI);
}